### ISSUE TITLE
[2017.5] Debian 8 failing integration.states.test_pip test on Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#337] opened 2017-05-10 17:08 UTC
The `integration.states.test_pip.PipStateTest.test_pip_installed_weird_install` is failing on the [2017.5 Python 3](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/) tests for Debian 8:
```
Error Message

False is not True. Salt Comment: Failed to install packages: carbon. Error: Collecting carbon   Downloading carbon-1.0.1.tar.gz (61kB)     Complete output from command python setup.py egg_info:     Traceback (most recent call last):       File "<string>", line 20, in <module>       File "/tmp/pip-build-v6jqsgpn/carbon/setup.py", line 6, in <module>         import ConfigParser     ImportError: No module named 'ConfigParser'          ---------------------------------------- You are using pip version 6.1.1, however version 9.0.1 is available. You should consider upgrading via the 'pip install --upgrade pip' command.     Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v6jqsgpn/carbon
Stacktrace

Traceback (most recent call last):
  File "//testing/tests/support/mixins.py", line 541, in assertSaltTrueReturn
    self.assertTrue(self.__getWithinSaltReturn(ret, 'result'))
  File "/usr/lib/python3.4/unittest/case.py", line 654, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//testing/tests/support/helpers.py", line 964, in decorator
    return func(cls, grains=cls.run_function('grains.items'))
  File "/testing/tests/integration/states/test_pip.py", line 121, in test_pip_installed_weird_install
    self.assertSaltTrueReturn(ret)
  File "//testing/tests/support/mixins.py", line 547, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
Failed to install packages: carbon. Error: Collecting carbon
  Downloading carbon-1.0.1.tar.gz (61kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-v6jqsgpn/carbon/setup.py", line 6, in <module>
        import ConfigParser
    ImportError: No module named 'ConfigParser'
    
    ---------------------------------------- You are using pip version 6.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v6jqsgpn/carbon
```

**Comment by rallytime** [comment] 2017-05-10 17:26
Somewhat related to #338.

**Comment by garethgreenaway** [comment] 2017-05-17 22:06
Running the single test for this one I can't reproduce it.

**Comment by rallytime** [comment] 2017-05-23 18:58
There is probably something else interacting with it, so it will probably require running more than the single test. Can you reproduce it running the whole file? Or maybe all of the state integration tests (`-S` option) or other testing sections that come before it to narrow down what might be affecting this test (module integration tests, perhaps)?

It failed again on some distros. Here's some links for reference:
- https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/job/salt-linode-py3-debian8/lastCompletedBuild/testReport/
- https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/job/salt-linode-py3-fedora25/lastCompletedBuild/testReport/
- https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/job/salt-lin-py3-ubuntu16/lastCompletedBuild/testReport/

**Comment by rallytime** [comment] 2017-05-23 18:58
whoops, forgot to mention you @garethgreenaway ^

**Comment by Ch3LL** [comment] 2017-05-25 13:25
@garethgreenaway any update on this? This is dependent on nitrogen.

**Comment by Ch3LL** [comment] 2017-05-25 13:27
Oh i just noticed @rallytime 's note in https://github.com/saltstack/salt-jenkins/issues/338#issuecomment-303499783 looks like this is a duplicate of that issue as well. Who can take a look at this @terminalmage or @garethgreenaway ?

**Comment by terminalmage** [comment] 2017-05-25 14:03
This is failing because ConfigParser does not exist in Python 3. The page for carbon on PyPI confirms that this is a Python-2-only module: https://pypi.python.org/pypi/carbon/1.0.1

We either need to skip this test on PY3 or just find a different target.

**Comment by terminalmage** [comment] 2017-05-25 14:04
@garethgreenaway can you make sure you were testing using Python 3?

**Comment by terminalmage** [comment] 2017-05-25 14:31
Looking back at the issue that this test was written for, it seems like the functionality being tested may be specific to the ``carbon`` package from PyPI. So, I'm just going to skip on PY3.

**Comment by terminalmage** [comment] 2017-05-25 14:40
https://github.com/saltstack/salt/pull/41427 skips this test. Closing.

**Closed by terminalmage** 2017-05-25 14:40 UTC
Labels: Cannot Reproduce, Python 3
