### ISSUE TITLE
Python 3 Fix test: AzureTest.test_instance

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#398] opened 2017-06-01 14:44 UTC
Currently the test `integration.cloud.providers.test_msazure.AzureTest.test_instance` is failing on python3 salt-cloud tests on the head of nitrogen with the error:

```
10:02:48    -> integration.cloud.providers.test_msazure.AzureTest.test_instance  ........
10:02:48        Traceback (most recent call last):
10:02:48          File "/testing/tests/integration/cloud/providers/test_msazure.py", line 139, in test_instance
10:02:48            ), timeout=TIMEOUT
10:02:48        AssertionError: 'CLOUD-TEST-Q9E3DA' not found in []
```

**Comment by rallytime** [comment] 2017-06-01 18:29
This looks like it is a duplicate of #397. Please let me know if this is incorrect @Ch3LL.

**Closed by rallytime** 2017-06-01 18:29 UTC
Labels: nitrogen, Python 3, salt-cloud
