### ISSUE TITLE
[Python 3] Fix unit.states.test_grains.GrainsTestCase.test_list_present_inexistent_nested  

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#431] opened 2017-06-20 14:45 UTC
Currently the test `unit.states.test_grains.GrainsTestCase.test_list_present_inexistent_nested ` is failing on Python3 Centos7. Here is the stacktrace/error:

```
Error Message

cannot represent an object: defaultdict(<function <lambda> at 0x7f7531b33510>, {'is': defaultdict(<function <lambda> at 0x7f7531b33510>, {'nested': ['baz']})})
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/states/test_grains.py", line 916, in test_list_present_inexistent_nested
    value='baz')
  File "/testing/salt/states/grains.py", line 204, in list_present
    new_grains = __salt__['grains.append'](name, value)
  File "/testing/salt/modules/grains.py", line 370, in append
    return setval(key, grains)
  File "/testing/salt/modules/grains.py", line 313, in setval
    return setvals({key: val}, destructive)
  File "/testing/salt/modules/grains.py", line 269, in setvals
    cstr = yaml.safe_dump(grains, default_flow_style=False)
  File "/usr/lib64/python3.4/site-packages/yaml/__init__.py", line 216, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/usr/lib64/python3.4/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python3.4/site-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/usr/lib64/python3.4/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python3.4/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/usr/lib64/python3.4/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python3.4/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/lib64/python3.4/site-packages/yaml/representer.py", line 229, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
yaml.representer.RepresenterError: cannot represent an object: defaultdict(<function <lambda> at 0x7f7531b33510>, {'is': defaultdict(<function <lambda> at 0x7f7531b33510>, {'nested': ['baz']})})
```

https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-cent7/131/testReport/junit/unit.states.test_grains/GrainsTestCase/test_list_present_inexistent_nested/

**Comment by cachedout** [comment] 2017-06-20 16:28
Thus far, I can't duplicate this on Cent7

**Comment by DmitryKuzmenko** [comment] 2017-06-21 17:35
It's more than strange because the `safe_dump` codeline is prepended by
```python
    yaml.representer.SafeRepresenter.add_representer(collections.defaultdict,
            yaml.representer.SafeRepresenter.represent_dict)
    yaml.representer.SafeRepresenter.add_representer(OrderedDict,
            yaml.representer.SafeRepresenter.represent_dict)
    cstr = yaml.safe_dump(grains, default_flow_style=False)
```

**Comment by cachedout** [comment] 2017-06-22 20:26
Maybe a different version of pyyaml is installed on the test machine?

**Comment by DmitryKuzmenko** [comment] 2017-06-23 08:55
The same. Checked it already.
Anyway, @terminalmage has a progress with it in scope of #434

**Comment by terminalmage** [comment] 2017-06-27 03:01
This is a duplicate of #434 (just a different platform), and was fixed by https://github.com/saltstack/salt/pull/41938

**Closed by terminalmage** 2017-06-27 03:01 UTC
Labels: nitrogen, Python 3
