### ISSUE TITLE
[2017.5] Several distros failing 2 tests in integration.runners.test-manage test on Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#341] opened 2017-05-10 17:23 UTC
The there are two tests failing on the [2017.5 Python 3](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/) tests for several on Ubuntu 16 and Ubuntu 17.

One test is `integration.runners.test_manage.ManageTest.test_up`:
```
Traceback (most recent call last):
  File "/testing/tests/integration/runners/test_manage.py", line 21, in test_up
    self.assertIn('minion', ret['return'])
AssertionError: 'minion' not found in []
```

The other tests is `integration.runners.test_manage.ManageTest.test_down`:
```
Traceback (most recent call last):
  File "/testing/tests/integration/runners/test_manage.py", line 31, in test_down
    self.assertNotIn('minion', ret['return'])
AssertionError: 'minion' unexpectedly found in ['sub_minion', 'minion']
```
Distros this fails on:
- Fedora 24
-  SUSE LEAP
- Ubuntu 16.04
- Ubuntu 17.04

**Comment by terminalmage** [comment] 2017-05-22 19:47
Can't reproduce on Ubuntu 17.04

**Comment by rallytime** [comment] 2017-05-23 19:18
These tests are still failing frequently on various distros for Python 3. Like other issues I commented on today, I think this one will need some more digging. Sounds like something earlier in the tests is interfering with these test results.

Here's the link to the latest Ubuntu 17 run: https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/job/salt-linode-py3-ubuntu17/lastCompletedBuild/testReport/.

**Comment by terminalmage** [comment] 2017-05-24 06:48
Yeah, I tried to run the entire suite and got bitten by the unittest2 memory leak, so I wasn't able to get the entire suite to complete.

I'll try to take a look at the logs and see what they might be able to tell me. From the results of these tests, it appears that the ``minion`` salt-minion instance is not responding to a ``test.ping``, since that is what ``manage.up`` and ``manage.down`` do.

**Comment by terminalmage** [comment] 2017-05-24 06:49
It may be possible that memory issues are causing the ``test.ping`` not to respond.

**Comment by rallytime** [comment] 2017-05-25 18:37
Yeah let's see how this goes. I don't see this on the latest test runs failing right now, so maybe this has cleared up. Let's leave this open for now and see how it goes over the next couple of days.

**Comment by terminalmage** [comment] 2017-05-30 14:29
It looks like the Ubuntu 17 tests haven't run in a few days.

**Comment by terminalmage** [comment] 2017-05-30 14:33
Actually, I think I might have found a possible explanation. Looking at the salt-runtests.log for the most recent run, I found this:

```
[ERROR   ] Problem executing 'test.ping': Minion in blackout mode. Set 'minion_blackout' to False in pillar to resume operations. Only saltutil.refresh_pillar allowed in blackout mode.
```

It's possible that one of the tests is overriding the in-memory pillar data. I'm digging further now.

**Comment by terminalmage** [comment] 2017-05-30 14:45
Actually no, this error only occurs during the blackout test, when it should.

**Comment by cachedout** [comment] 2017-06-01 22:47
@terminalmage Can you come back to this one in the morning?

**Comment by terminalmage** [comment] 2017-06-02 05:52
Yeah, I'll take another look.

**Comment by terminalmage** [comment] 2017-06-02 13:56
This no longer appears to be failing. From the most recent build's [console log](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/job/salt-linode-py3-ubuntu17/64/consoleFull):

```
01:14:30 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
01:14:30 Starting Runners Tests
01:14:30 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
01:14:30 
01:14:30 Running tests...
01:14:30 ----------------------------------------------------------------------
01:14:30   test_cache (integration.runners.test_cache.ManageTest)
01:14:36 [CPU:23.1%|MEM:17.2%]  ... OK (5.882s)
01:14:36   test_clear_file_list_cache (integration.runners.test_fileserver.FileserverTest)
01:14:51 [CPU:0.0%|MEM:17.4%]  ... OK (15.631s)
01:14:51   test_dir_list (integration.runners.test_fileserver.FileserverTest)
01:14:53 [CPU:0.0%|MEM:17.5%]  ... OK (1.883s)
01:14:53   test_empty_dir_list (integration.runners.test_fileserver.FileserverTest)
01:14:55 [CPU:0.0%|MEM:17.5%]  ... OK (2.227s)
01:14:55   test_envs (integration.runners.test_fileserver.FileserverTest)
01:14:57 [CPU:0.0%|MEM:17.5%]  ... OK (2.068s)
01:14:57   test_file_list (integration.runners.test_fileserver.FileserverTest)
01:14:59 [CPU:0.0%|MEM:17.5%]  ... OK (1.999s)
01:14:59   test_symlink_list (integration.runners.test_fileserver.FileserverTest)
01:15:02 [CPU:0.0%|MEM:17.7%]  ... OK (2.638s)
01:15:02   test_update (integration.runners.test_fileserver.FileserverTest)
01:15:05 [CPU:0.0%|MEM:17.7%]  ... OK (2.579s)
01:15:05   test_active (integration.runners.test_jobs.ManageTest)
01:15:06 [CPU:100.0%|MEM:17.9%]  ... OK (1.647s)
01:15:06   test_list_jobs (integration.runners.test_jobs.ManageTest)
01:15:06 [CPU:50.0%|MEM:17.9%]  ... SKIP (0.002s)
01:15:06   test_lookup_jid (integration.runners.test_jobs.ManageTest)
01:15:08 [CPU:0.0%|MEM:17.9%]  ... OK (1.648s)
01:15:08   test_down (integration.runners.test_manage.ManageTest)
01:15:09 [CPU:0.0%|MEM:17.9%]  ... OK (1.275s)
01:15:09   test_up (integration.runners.test_manage.ManageTest)
01:15:10 [CPU:0.0%|MEM:17.9%]  ... OK (0.928s)
01:15:10   test_runner_returns_disabled (integration.runners.test_runner_returns.RunnerReturnsTest)
01:15:11 [CPU:0.0%|MEM:17.9%]  ... OK (1.203s)
01:15:11   test_runner_returns_enabled (integration.runners.test_runner_returns.RunnerReturnsTest)
01:15:13 [CPU:0.0%|MEM:17.9%]  ... OK (1.477s)
01:15:13   test_salt_cmd (integration.runners.test_salt.SaltRunnerTest)
01:15:14 [CPU:0.0%|MEM:17.9%]  ... OK (0.823s)
01:15:14   test_jid_in_ret_event (integration.runners.test_state.OrchEventTest)
01:15:15 [CPU:0.0%|MEM:17.9%] 01:15:15,612 [salt.template                              :62  ][ERROR   ] Template was specified incorrectly: False
01:15:16 01:15:15,808 [salt.state                                 :266 ][ERROR   ] Run failed on minions: minion
01:15:16 Failures:
01:15:16     minion:
01:15:16         Data failed to compile:
01:15:16     ----------
01:15:16         No matching sls found for 'test_state' in env 'base'
01:15:16 
01:15:18  ... OK (4.316s)
01:15:18   test_orchestrate_nested (integration.runners.test_state.StateRunnerTest)
01:15:23 [CPU:0.0%|MEM:17.9%] [ERROR   ] {'out': 'highstate', 'ret': {'minion': ''}}
01:15:23 [ERROR   ] {'data': {'master': {'salt_|-cmd.run_|-cmd.run_|-function': {'__id__': 'cmd.run', 'name': 'cmd.run', 'duration': 308.01, 'changes': {'out': 'highstate', 'ret': {'minion': ''}}, '__sls__': 'nested-orch.inner', 'start_time': '01:15:23.067069', '__run_num__': 0, '__jid__': '20170602011523156434', 'comment': 'Running function cmd.run failed on minions: minion Function cmd.run ran on minion.', 'result': False}}}, 'retcode': 1, 'outputter': 'highstate'}
01:15:23 01:15:23,248 [salt.loader.localhost.int.module.cmdmod    :949 ][ERROR   ] Command '/bin/false' failed with return code: 1
01:15:23 01:15:23,249 [salt.loader.localhost.int.module.cmdmod    :950 ][ERROR   ] output: 
01:15:23 01:15:23,374 [salt.state                                 :266 ][ERROR   ] {'out': 'highstate', 'ret': {'minion': ''}}
01:15:23 01:15:23,385 [salt.state                                 :266 ][ERROR   ] {'data': {'master': {'salt_|-cmd.run_|-cmd.run_|-function': {'__id__': 'cmd.run', 'name': 'cmd.run', 'duration': 308.01, 'changes': {'out': 'highstate', 'ret': {'minion': ''}}, '__sls__': 'nested-orch.inner', 'start_time': '01:15:23.067069', '__run_num__': 0, '__jid__': '20170602011523156434', 'comment': 'Running function cmd.run failed on minions: minion Function cmd.run ran on minion.', 'result': False}}}, 'retcode': 1, 'outputter': 'highstate'}
01:15:24  ... OK (5.639s)
01:15:24   test_orchestrate_output (integration.runners.test_state.StateRunnerTest)
01:15:29 [CPU:0.0%|MEM:18.0%]  ... OK (5.701s)
01:15:29   test_state_event (integration.runners.test_state.StateRunnerTest)
01:15:33 [CPU:0.0%|MEM:18.0%]  ... OK (3.979s)
01:15:33 
01:15:33 ----------------------------------------------------------------------
01:15:33 Ran 20 tests in 63.569s
01:15:33 
01:15:33 OK (skipped=1)
```

**Comment by rallytime** [comment] 2017-06-02 14:50
Hmm, I saw it fail on a build just yesterday [right here](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/job/salt-linode-py3-ubuntu17/63/), but I don't see it on the last run. I think this is a flaky test that is having problems in PY3. It appears from this discussion that this test has a habit of clearing up and then reappearing (as seen in [this comment](https://github.com/saltstack/salt-jenkins/issues/341#issuecomment-304088841)).

**Comment by rallytime** [comment] 2017-06-02 14:51
@terminalmage and @cachedout ^

**Comment by terminalmage** [comment] 2017-06-02 16:18
Yeah, but these tests are pretty straightforward. These two runners both do the same thing: run test.ping on all minions with accepted keys. The weird thing here is that the ``test_down`` test is failing at the same time as the ``test_up`` test, which doesn't really make sense. If anything, the ``test_up`` test should fail while the ``test_down`` one should pass. With both failing, this suggests that the minions are up when ``test_down`` is run, but magically also down with ``test_up`` is run.

I've added some debug logging in https://github.com/saltstack/salt/pull/41564. Once we get that merged, hopefully the salt-runtests.log from the jenkins build can give us some more insight.

**Comment by terminalmage** [comment] 2017-06-06 13:21
After getting some debug logging merged, it looks like when there is a failure it is because the return event never got fired to the master. See [this gist](https://gist.github.com/terminalmage/6e6594e8a1f69b65de21981fb7e0c1ea) for an example. In this case, only the manage_down job failed. There are no ``fn_ret`` log lines in the logging for that test, which means there were no events returned by the ``get_cli_event_returns`` generator.

The next step for looking into this would be to add logging into the ``get_cli_event_returns`` generator. My guess is that there is some condition not being considered by the logic in this generator, causing it not to yield results for that minion.

**Comment by terminalmage** [comment] 2017-06-06 13:24
https://github.com/saltstack/salt/pull/41606 reverts some of the debug logging that I've added and adds new logging to the ``get_cli_event_returns`` generator.

**Comment by terminalmage** [comment] 2017-06-06 16:48
OK, well that debug logging didn't do what I hoped it would. Instead of identifying problems with the `get_cli_event_returns` generator ignoring events from `get_iter_returns`, it instead shows that the returns themselves are unreliable. One of the things I added with the recent changes to the debug logging was to log all events coming out of `get_iter_returns`. What this showed in [this gist](https://gist.github.com/terminalmage/2dd0e7c585e1f0963138291496ef2c50) from a Debian 8 test run is that in the `test_down` test did not receive returns from either of the two minions, and `test_up` only received returns from one of the two minions.

**Comment by terminalmage** [comment] 2017-06-06 20:01
After adding yet more logging, it appears that the published command isn't even being executed by the targeted minions.

https://gist.github.com/terminalmage/546108bf0d4c2db4928534d26f83827c

You should be seeing log entries saying that a given minion has received the test.ping, as well as the event the minion returns to the master. In this case, both of the tests are failing because neither of the minions are even running the ping in the first place.

Again, this is intermittent, sometimes one of the minions will respond, and other times they won't.

**Comment by Ch3LL** [comment] 2017-06-20 15:01
Closing for now since this is probably related to memory issues. Will re-open if we see it again.

**Closed by Ch3LL** 2017-06-20 15:01 UTC
Labels: nitrogen, Python 3
