### ISSUE TITLE
[oxygen] CentOS 6 failing serializers unit test

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#784] opened 2018-01-22 20:33 UTC
- unit.serializers.test_serializers.TestSerializers.test_serialize_yaml
```
Traceback (most recent call last):
  File "/testing/tests/unit/serializers/test_serializers.py", line 52, in test_serialize_yaml
    assert serialized == '{encrypted_data: !encrypted foo, foo: bar}', serialized
AssertionError: {encrypted_data: !encrypted 'foo', foo: bar}
```
https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-cent6-py2/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment] 2018-01-23 19:33
Can't reproduce right now, I'm having Brett add the cent6 ec2 image to the dev box builder so I can try to reproduce on AWS.

**Comment by terminalmage** [comment] 2018-01-23 23:33
OK, after a bunch of troubleshooting I found that this comes down to a difference between the CSafeDumper and the SafeDumper. The yaml serializer will prefer the CSafeDumper if it is available. When serializing an instance of the EncryptedString, it will leave it unquoted, while the SafeDumper will quote it. So, because the Cent 6 image on AWS does not have the CSafeDumper available, it quotes the string.

Since both quoted and unquoted are valid YAML, there really is no reason to dig further, the fix here is to just assert on a string _with_ quotes when the CSafeDumper is not present, and on a string _without_ quote when the CSafeDumper _is_ present.

I'm working on some other Cent6 failures right now, and will submit a PR later tonight that fixes several tests.

**Comment by terminalmage** [comment] 2018-01-24 01:26
Fixed in https://github.com/saltstack/salt/pull/45658

**Closed** 2018-01-26 20:45 UTC
Labels: Fixed Pending Verification, Oxygen
