### ISSUE TITLE
[Python 3] Fix unit.states.test_grains.GrainsTestCase.test_list_present_inexistent_nested

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#434] opened 2017-06-20 14:54 UTC
Currently the test `unit.states.test_grains.GrainsTestCase.test_list_present_inexistent_nested` is failing on Fedora 24

```
Error Message

cannot represent an object: defaultdict(<function <lambda> at 0x7f264f230378>, {'is': defaultdict(<function <lambda> at 0x7f264f230378>, {'nested': ['baz']})})
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/states/test_grains.py", line 916, in test_list_present_inexistent_nested
    value='baz')
  File "/testing/salt/states/grains.py", line 204, in list_present
    new_grains = __salt__['grains.append'](name, value)
  File "/testing/salt/modules/grains.py", line 370, in append
    return setval(key, grains)
  File "/testing/salt/modules/grains.py", line 313, in setval
    return setvals({key: val}, destructive)
  File "/testing/salt/modules/grains.py", line 269, in setvals
    cstr = yaml.safe_dump(grains, default_flow_style=False)
  File "/usr/lib64/python3.5/site-packages/yaml/__init__.py", line 216, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/usr/lib64/python3.5/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python3.5/site-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/usr/lib64/python3.5/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python3.5/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/usr/lib64/python3.5/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python3.5/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/lib64/python3.5/site-packages/yaml/representer.py", line 229, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
yaml.representer.RepresenterError: cannot represent an object: defaultdict(<function <lambda> at 0x7f264f230378>, {'is': defaultdict(<function <lambda> at 0x7f264f230378>, {'nested': ['baz']})})
```

https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-fedora24/135/testReport/junit/unit.states.test_grains/GrainsTestCase/test_list_present_inexistent_nested/

**Comment by terminalmage** [comment] 2017-06-22 15:02
I haven't been able to reproduce this yet. I've tried in Docker, as well as a Vagrant box, both with salt-jenkins used to install the test deps from the 2017.7 branch. My next step will be to spin up a cloud instance and try the test there.

**Comment by terminalmage** [comment] 2017-06-22 18:02
With some help from Brett I got a Linode VM up. I still can't reproduce this failure when running the test standalone, but I _can_ get it to fail when running the unit tests as a whole (which I couldn't do on my Vagrant box). So, progress!

Since this is a unit test and there are no daemons, I'm now re-running the unit tests with the failing test set to launch pudb.

**Comment by terminalmage** [comment] 2017-06-26 16:57
Fixed in https://github.com/saltstack/salt/pull/41938.

**Closed by terminalmage** 2017-06-26 16:57 UTC
Labels: nitrogen, Python 3
