### ISSUE TITLE
Debian 8 issues with tornado

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#549] opened 2017-11-10 15:50 UTC
Debian 8 tests are experiencing a variety of failures on each branch and in both Pythin 2 tests and Python 3.

In some cases (such as on the 2016.11 branch), all of the tests are failing in the netapi integration tests (`integration.netapi.rest_tornado.test_app.x`). In other cases, we don't even get to the point of running the tests due to problems with tornado.

This may be due to the version of tornado running on Debian 8 or what we are installing in the salt-jenkins states. However, this is just my guess and would need to be investigated more.

Keep in mind there are problems with the Debian 8 tests in ALL of our release branches. So those failures would need to be handled in kind.

**Comment by Ch3LL** [comment] 2018-01-08 20:54
I don't see this failing on oxygen branch so removing oxygen label for now

**Comment by Ch3LL** [comment] 2018-01-10 21:17
okay this is the cause: https://github.com/tornadoweb/tornado/issues/1573 which has been fixed in newer tornado versions. So will need to look at salt-jenkins states to make sure we are installing latest tornado available for debian.

**Comment by Ch3LL** [comment] 2018-01-11 16:23
started a test here: https://jenkins.saltstack.com/job/2016.9/job/salt-2016_9-linode-debian8/1564/console to see if deb8 passes now

**Comment by Ch3LL** [comment] 2018-01-11 17:34
Looks like this indeed solved the failing tornado api tests :)

**Closed by Ch3LL** 2018-01-11 17:34 UTC
Labels: 2016.11.9, 2017.7.3, Fixed Pending Verification
