### ISSUE TITLE
[2018.3.3] arch python3 tests do not finish

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1075] opened 2018-08-16 13:33 UTC
Currently the python3 arch tests are not finishing tests and timeout.

https://jenkinsci.saltstack.com/job/2018.3.3/view/Python3/job/salt-arch-py3/4/console

**Comment by Ch3LL** [comment] 2018-08-17 13:17
ping @garethgreenaway any chance you can take a look here. 

i noticed all hte builds are timing out on this part:

```
test_exit_status_correct_usage (integration.shell.test_minion.MinionTest)
```

**Comment by Ch3LL** [comment] 2018-08-22 20:43
any update on this @garethgreenaway

**Comment by garethgreenaway** [comment] 2018-08-22 20:44
@Ch3LL Unfortunately I still haven't been able to find the cause.  It's definitely something in Python 3.7 and not specific to Arch though.

**Comment by Ch3LL** [comment] 2018-08-28 13:27
unfortunately it looks like this is still hanging: https://jenkinsci.saltstack.com/job/2018.3.3/view/Python3/job/salt-arch-py3/15/console

not sure if you knew @garethgreenaway

**Comment by gtmanfred** [comment] 2018-08-30 23:25
https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-arch-py3/37/console

At least it is in unittests now.

**Comment by rallytime** [comment] 2018-08-31 15:30
Oops, that closed automatically when it shouldn't have. :)

@garethgreenaway Can you make this your priority when you get back? @gtmanfred is currently on PTO, but there should be some more info in here from his work this week to get this moving again.

**Comment by rallytime** [comment] 2018-09-07 13:43
Nice! These are no longer hanging, but we have a bunch of failures around the `errno` missing. Let's get those fixed up too.

**Comment by rallytime** [comment] 2018-09-26 12:55
This is fixed now.

**Closed by rallytime** 2018-09-26 12:55 UTC
Labels: 2018.3.3, Fixed Pending Verification
