### ISSUE TITLE
[fluorine] docker test failures in transport tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1240] opened 2018-12-11 15:17 UTC
integration.states.test_docker_container.DockerContainerTestCase.test_running_updated_image_id
integration.modules.test_dockermod.DockerCallTestCase.test_docker_call
integration.modules.test_dockermod.DockerCallTestCase.test_docker_highstate
integration.modules.test_dockermod.DockerCallTestCase.test_docker_sls

failing here: https://jenkinsci.saltstack.com/job/fluorine/view/Transport/job/salt-centos-7-py3-transport/

**Comment by terminalmage** [comment] 2018-12-14 18:52
Can't reproduce these failures, and these have been passing for 3 consecutive days (with the test from today still pending as a 4th).

Whatever this was, seems to have been transitory. Closing this.

**Closed by terminalmage** 2018-12-14 18:52 UTC
Labels: Fluorine
