### ISSUE TITLE
Python3 Fix Test: JoyentTest.test_instance

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#396] opened 2017-06-01 14:40 UTC
Currently the following test: `integration.cloud.providers.test_joyent.JoyentTest.test_instance` is failing on python3 salt-cloud tests with the error:

```
10:02:48    -> integration.cloud.providers.test_joyent.JoyentTest.test_instance  ........
10:02:48        Traceback (most recent call last):
10:02:48          File "/testing/tests/integration/cloud/providers/test_joyent.py", line 88, in test_instance
10:02:48            [i.strip() for i in self.run_cloud('-p joyent-test {0}'.format(INSTANCE_NAME), timeout=500)]
10:02:48        AssertionError: 'CLOUD-TEST-KUY7Q5' not found in []
```

**Comment by rallytime** [comment] 2017-06-01 22:54
@Ch3LL This should be fixed by https://github.com/saltstack/salt/pull/41558, but let's see how the cloud tests go in case I missed something. Please let me know how the test run goes after that PR is merged.

**Comment by rallytime** [comment] 2017-06-05 22:55
@Ch3LL Did this one fail? I see you removed the label, but I didn't see a comment from you. I don't have joyent configured currently, so just checking before I go down this road.

**Comment by Ch3LL** [comment] 2017-06-06 15:27
Yes it failed. Apologies, I must not have hit comment button

**Comment by rallytime** [comment] 2017-06-08 23:26
The issue here is that on PY3, when the `RSA.importkey` function is called [here](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/joyent.py#L1074), the library's own PY2/3 compat chokes on the type coming in from the file handle. If `rsa_key = RSA.importKey(kh_)` is changed to `rsa_key = RSA.importKey(kh_.read())` in order for the `importKey` function to not stacktrace, we then hit a new stacktrace around updating the `hash_` with `timestamp`.

`timestamp` must be encoded before updating the hash in PY3. That's fine. Just add a new line line `encoded = salt.utils.to_bytes(timestamp)` and update the variable on line 1077.

Now the problem is that the once we get through these two stacktraces with the changes mentioned above, we cannot authenticate to the joyent API. It returns a 401 error.

I reached out to @techhat about this today, but we have not reached a solution.

**Comment by rallytime** [comment] 2017-06-09 16:05
Another point of reference:

If you keep the `rsa_key = RSA.importKey(kh_)` line as it currently is in the code (without the `read()`), and change the mode the file is opened in to `rb` instead of just `r`, you get the following stacktrace:
```
[ERROR   ] Failed to get the output of 'joyent.avail_images()': 'bytes' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/testing/salt/cloud/__init__.py", line 869, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/testing/salt/cloud/clouds/joyent.py", line 846, in avail_images
    rcode, data = query(command='my/images', method='GET')
  File "/testing/salt/cloud/clouds/joyent.py", line 1077, in query
    rsa_key = RSA.importKey(kh_)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/PublicKey/RSA.py", line 628, in importKey
    externKey = tobytes(externKey)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Util/py3compat.py", line 105, in tobytes
    return bytes(s)
TypeError: 'bytes' object cannot be interpreted as an integer
```

**Comment by rallytime** [comment] 2017-07-24 21:11
@gtmanfred Fixed this with https://github.com/saltstack/salt/pull/42529

**Closed** 2017-07-28 15:07 UTC
Labels: Fixed Pending Verification, nitrogen, Python 3, salt-cloud
