### ISSUE TITLE
[oxygen] salt-cloud rackspace tests failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#682] opened 2018-01-08 21:18 UTC
```
14:07:36    -> integration.cloud.providers.test_rackspace.RackspaceTest.test_instance  ..
14:07:36        Traceback (most recent call last):
14:07:36          File "/testing/tests/integration/cloud/providers/test_rackspace.py", line 83, in test_instance
14:07:36            [i.strip() for i in self.run_cloud('-p rackspace-test {0}'.format(INSTANCE_NAME), timeout=500)]
14:07:36        AssertionError: u'CLOUD-TEST-CN3VNK' not found in []
```

**Comment by Ch3LL** [comment] 2018-01-08 21:26
Found stack trace in cloud log:

```
13:31:01 [ERROR   ] Error key_name: None is not of type (<type 'basestring'>,)
13:31:01 13:31:01,445 [salt.loaded.int.clouds.openstack           :588 ][ERROR   ] Error key_name: None is not of type (<type 'basestring'>,)
13:32:00 [ERROR   ] Failed to create VM CLOUD-TEST-CN3VNK. Configuration value u'OS-EXT-IPS:type' needs to be set
13:32:00 Traceback (most recent call last):
13:32:00   File "/testing/salt/cloud/__init__.py", line 1283, in create
13:32:00     output = self.clouds[func](vm_)
13:32:00   File "/testing/salt/cloud/clouds/openstack.py", line 678, in create
13:32:00     data = request_instance(conn=conn, call='action', vm_=vm_)
13:32:00   File "/testing/salt/cloud/clouds/openstack.py", line 632, in request_instance
13:32:00     return show_instance(vm_['name'], conn=conn, call='action')
13:32:00   File "/testing/salt/cloud/clouds/openstack.py", line 449, in show_instance
13:32:00     ret['floating_ips'] = _get_ips(node, 'floating')
13:32:00   File "/testing/salt/cloud/clouds/openstack.py", line 358, in _get_ips
13:32:00     if addr_type in ('floating', 'fixed') and addr_type == addr['OS-EXT-IPS:type']:
13:32:00 KeyError: u'OS-EXT-IPS:type'
13:32:00 13:32:00,287 [salt.cloud                                 :1322][ERROR   ] Failed to create VM CLOUD-TEST-CN3VNK. Configuration value u'OS-EXT-IPS:type' needs to be set
13:32:00 Traceback (most recent call last):
13:32:00   File "/testing/salt/cloud/__init__.py", line 1283, in create
13:32:00     output = self.clouds[func](vm_)
13:32:00   File "/testing/salt/cloud/clouds/openstack.py", line 678, in create
13:32:00     data = request_instance(conn=conn, call='action', vm_=vm_)
13:32:00   File "/testing/salt/cloud/clouds/openstack.py", line 632, in request_instance
13:32:00     return show_instance(vm_['name'], conn=conn, call='action')
13:32:00   File "/testing/salt/cloud/clouds/openstack.py", line 449, in show_instance
13:32:00     ret['floating_ips'] = _get_ips(node, 'floating')
13:32:00   File "/testing/salt/cloud/clouds/openstack.py", line 358, in _get_ips
13:32:00     if addr_type in ('floating', 'fixed') and addr_type == addr['OS-EXT-IPS:type']:
13:32:00 KeyError: u'OS-EXT-IPS:type'
13:32:00 Error: There was a profile error: Failed to deploy VM
```

ping @gtmanfred any chance you see the issue at first glance? If not I can dive in

**Comment by gtmanfred** [comment] 2018-01-08 22:33
Yeah i think the problem is we just need to change that `addr['OS-EXT-IPS:type']` to use `.get`

**Comment by gtmanfred** [comment] 2018-02-06 21:17
I have a fix for the os-ext-ips problem.  But we need to add an `ssh_keyfile` option for the new one.  

I am assigning this back to you @Ch3LL to add that since I don't know how your states are currently setup for that, and don't want to break them, but we just need an ssh key for the salt-jenkins user to use to attach to the server and then specified as `ssh_key_name` to the name that it is in rackspace for the public key, and then `ssh_key_file` for the path to the private key on the cloud test box.

Daniel

**Closed** 2018-02-08 16:27 UTC
Labels: Oxygen
