### ISSUE TITLE
[2017.5] Fix GCE Cloud Tests

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#321] opened 2017-05-03 20:03 UTC
@Ch3LL commented on [Thu Apr 27 2017](https://github.com/saltstack/zh/issues/1277)

**Comment by Ch3LL** [comment] 2017-05-25 19:49
This is the error i'm seeing in the tests:

```
Traceback (most recent call last):
  File "/testing/salt/cloud/clouds/gce.py", line 2512, in request_instance
    node_data = conn.create_node(**kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 2598, in create_node
    location))
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 4505, in ex_get_subnetwork
    response = self.connection.request(request, method='GET').object
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 121, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/google.py", line 778, in request
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 862, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 181, in __init__
    self.object = self.parse_body()
  File "/usr/lib/python2.7/site-packages/libcloud/common/google.py", line 269, in parse_body
    raise ResourceNotFoundError(message, self.status, code)
ResourceNotFoundError: {u'domain': u'global', u'message': u"The resource 'projects/test:salt/regions/us-central1/subnetworks/default' was not found", u'reason': u'notFound'}
Error: There was a profile error: There was an error creating the GCE instance.
```

I think this was caused by github.com/saltstack/salt/pull/39072/files and we are using the old gce and do not have a default subnetwork, but the code assumes we do. I think this was written for new gce instances as the note here suggests: https://github.com/saltstack/salt/pull/39183/files#diff-0d1d6f19977b0413cbac1a26a4f5cad2R222  I am still digging in more to see if this is indeed the cause.

**Comment by Ch3LL** [comment] 2017-05-25 20:38
https://github.com/saltstack/salt/pull/41437 i'm not 100% sure this is the right fix so I will keep this open until confirmed its accurate or not.

**Comment by Inveracity** [comment] 2017-05-26 18:49
I added that code because the documentation for GCE states:
```
Every project comes with a default network that is automatically created. The default network is an auto mode VPC network
```
I believe if you create a new organization/project it'll be there, but I think this was something that got added to GCE after the original gce module was written for salt - but that's a guess

**Comment by Ch3LL** [comment] 2017-06-01 13:19
I think thats only for the new vpc network modes, because we currently use an old vpc network setup a while ago and there is no default subnetwork. So looks like the fix was merged so its just not a default anymore is all. Thanks :)

**Closed by Ch3LL** 2017-06-01 13:19 UTC
