### ISSUE TITLE
[2016.11] CentOS 6 fails in git.salt state run

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#476] opened 2017-08-10 16:14 UTC
The CentOS 6 box on 2016.11 isn't building due to an error in the `git.salt` state run:

https://jenkins.saltstack.com/job/branch_tests/job/2016.9/job/salt-2016_9-linode-cent6/lastFailedBuild/console

It looks like this has been failing for quite a while. We need to get this fixed.

**Comment by terminalmage** [comment] 2017-08-10 16:52
Well first things first, it looks like this is using Python 2.6 instead of 2.7. @rallytime where is it getting the bootstrap script?

**Comment by rallytime** [comment] 2017-08-10 16:53
@terminalmage 2016.11 should still be using Python 2.6.

**Comment by terminalmage** [comment] 2017-08-10 16:57
/me nods

OK, I forgot when we officially deprecated 2.6. Good to rule that out.

**Comment by terminalmage** [comment] 2017-08-11 12:56
This appears to be caused by two things. First, we are removing pycrypto which
is interrupting the state.sls. This was supposedly being done because we weren't packaging pycrypto >= 2.6.1, but we've been doing that for a while now.

After fixing this via #482 and #483, I found that now the CherryPy installation fails. Version 11.0.0 of CherryPy (released 8 July 2017) dropped support for Python 2.6. I have opened #484 to force installation of a version earlier than 11.0.0 on boxes running Python 2.6.

We'll have to see if there are further failures once #484 has been merged.

**Comment by terminalmage** [comment] 2017-08-11 15:43
Also needed to pin another CherryPy dep to an earlier version, did this in #485

**Comment by terminalmage** [comment] 2017-08-11 15:57
git.salt is working now, closing this issue. We can open separate issues if there are test failures in the branch build.

Build is here: https://jenkins.saltstack.com/job/branch_tests/job/2016.9/job/salt-2016_9-linode-cent6/1490/console

**Closed by terminalmage** 2017-08-11 15:57 UTC
Labels: 2016.11.8
