### ISSUE TITLE
Tests hanging on integration.modules.test_cp.CPModuleTest.test_cache_remote_file

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#854] opened 2018-02-27 15:48 UTC
I have seen this failing on multiple branches.

Here's an example from 2017.7 (note this has been running for 3 days...):
https://jenkins.saltstack.com/job/2017.7/job/2017.7-salt-fedora27-py3/92/console

Here's an example on 2018.3:
https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-ubuntu17.04-py3/114/console

And here is an example from 2018.3.0rc1:
https://jenkins.saltstack.com/job/2018.3.0rc1/job/oxygen-salt-debian9-py3/32/console

You can see the list of builds hanging in the build executors list on the left of jenkins: https://jenkins.saltstack.com/  

The builds towards the top of the list are all hanging and taking _way_ too long. They all seem to be PY3 builds.

**Comment by terminalmage** [comment] 2018-02-27 23:12
This was caused by a combination of two things.

First, jobs were timing out because a critical bug in msgpack-python 0.5.5 (see https://github.com/msgpack/msgpack-python/commit/da902f9c1d996fb461f1efef6487ef40d32d365a#r27725642), causing jobs to timeout and return False.

Second, `open()` on Python 3 treats the integer values of boolean `True` and `False` as file descriptors, so a `False` was causing an open in `test_cache_remote_file` to block indefinitely on stdin.

The first issue was fixed in https://github.com/saltstack/salt/pull/46221, the second in https://github.com/saltstack/salt-jenkins/pull/856.

**Comment by terminalmage** [comment] 2018-02-28 02:03
All of the related PRs are now merged.

**Closed** 2018-02-28 15:05 UTC
Labels: Fixed Pending Verification
