### ISSUE TITLE
[fluorine] arch test_cp failure

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1225] opened 2018-11-28 20:49 UTC
integration.modules.test_cp.CPModuleTest.test_get_file_str_https

https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-arch-py3/48/

**Comment by terminalmage** [comment] 2018-12-07 15:30
I've opened https://github.com/saltstack/salt/pull/50788 to fix this. I was able to reproduce, but only the first time I ran the test. Subsequent runs worked. This appears to be some problem with DNS resolution, because I spawned another AWS box and the lookup for repo.saltstack.com failed using cURL initially, but then worked after that.

**Comment by terminalmage** [comment] 2018-12-07 21:21
The latest branch build shows this test passed. Closing.

**Closed by terminalmage** 2018-12-07 21:21 UTC
Labels: Fixed Pending Verification, Fluorine
